# Generated by Django 5.1 on 2024-08-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='country',
            field=models.CharField(default='Ukraine', max_length=200),
        ),
    ]
