# Generated by Django 5.1 on 2024-08-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_brand_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_new',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
