# Generated by Django 5.1 on 2024-08-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_price_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='main_image',
        ),
        migrations.AddField(
            model_name='product',
            name='forth_picture',
            field=models.ImageField(blank=True, default='1', null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='second_picture',
            field=models.ImageField(blank=True, default='1', null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='third_picture',
            field=models.ImageField(blank=True, default='1', null=True, upload_to='products'),
        ),
    ]
