# Generated by Django 5.1 on 2024-08-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_userdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'UserData', 'verbose_name_plural': 'UserData'},
        ),
    ]
