# Generated by Django 5.1 on 2024-08-20 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_wishlist_product_alter_wishlist_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
