# Generated by Django 5.1 on 2024-08-21 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_rename_image_reviewimage_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewimage',
            old_name='images',
            new_name='image',
        ),
    ]
