# Generated by Django 5.1 on 2024-08-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
